# Generated by Django 6.0.7 on 2026-08-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
