# Generated by Django 6.0.7 on 2026-08-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messe', '0002_message_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
