# Generated by Django 6.0.7 on 2026-08-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messe', '0003_message_image_alter_message_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
